### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by gootieno** [FremaAwuku/BublcatBuddies#1]
Hi! Just creating an example for how the routing should be written :) 

In wiki create a frontend routes ( you already have it) and backend routes

Fontend Routes
/ landing page
/login login page
/register registration page
/users/:id/events events belonging to a user
/events shows all events
/events/:id shows a single event 

These are just examples to sort of get an idea of how you should structure frontend routes

Backend Routes

/api/session authentication
/api/users/1 get a single user from database
/api/events get all the events from database
/api/users/1/events get all the events from user 1

These routes will be in your backend directory in the routes/api directory. We fetch to the backend routes to get the data to display when someone goes to a defined frontend route :) Hope this helps!!

Once you make changes you can mark issue as resolved!

**Comment by FremaAwuku** [comment]
got it done!!!
